ARG ACCT="C-Worthy"
ARG IMG_BUILDBASE="$ACCT/cstar-buildbase:latest"
ARG MAIN_STAGE="main"  # pass `add_test` to build the test program /runtest

FROM $IMG_BUILDBASE as main

ARG OPENMPI_URI="https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.7.tar.gz"
ARG OMPI_TGZ_NAME="openmpi-5.0.7.tar.gz" 
ARG OMPI_TGZ_OUT_DIR="openmpi-5.0.7"

ARG SRC_DIR="/install"
ARG INSTALL_BASE_DIR="/opt"
ENV MPIHOME="$INSTALL_BASE_DIR/$OMPI_TGZ_OUT_DIR"
ARG MPI_PROFILE="/etc/profile.d/ompi-5.0.7.sh"

RUN mkdir -p "$SRC_DIR"

RUN apt-get update && \
    apt-get install -y \
        # libpmi2-0-dev \
        libpmix-dev \
        openssh-client \
        # libssl \
        # slurm-wlm \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR "$SRC_DIR"
RUN wget -q "$OPENMPI_URI" && \
    tar xvf "$OMPI_TGZ_NAME" && \
    cd "$OMPI_TGZ_OUT_DIR" && \
    ./configure \
        --prefix="$MPIHOME" --with-pic \
        --with-slurm \
        --with-pmix=internal && \
                    # --with-pmi=/usr/include/slurm \
                    # --with-pmi-libdir=/usr/lib/x86_64-linux-gnu \
        # --with-pmix=/user/include/slurm && \
        # --with-pmix=/usr/lib/x86_64-linux-gnu/pmix2 && \
    make -j $(nproc) && make install && cd "$SRC_DIR" && \
    rm "$OMPI_TGZ_NAME" && \
    rm -rf "$OMPI_TGZ_OUT_DIR" && \
    ldconfig

ENV PATH="$MPIHOME/bin:$PATH"
ENV LD_LIBRARY_PATH="$MPIHOME/lib:$LD_LIBRARY_PATH"
ENV CPATH="$MPIHOME/include:$CPATH"
ENV LIBRARY_PATH="$MPIHOME/lib:$LIBRARY_PATH"
ENV LD_RUN_PATH="$MPIHOME/lib:$LD_RUN_PATH"

RUN mkdir -p "/etc/profile.d" && \
    echo "export MPIHOME=$MPIHOME" >> $MPI_PROFILE && \
    echo 'export PATH=$MPIHOME/bin:$PATH' >> $MPI_PROFILE && \
    echo 'export LD_LIBRARY_PATH=$MPIHOME/lib:$LD_LIBRARY_PATH' >> $MPI_PROFILE && \
    echo 'export CPATH=$MPIHOME/include:$CPATH' >> $MPI_PROFILE && \
    echo 'export LIBRARY_PATH=$MPIHOME/lib:$LIBRARY_PATH' >> $MPI_PROFILE && \
    echo 'export LD_RUN_PATH=$MPIHOME/lib:$LD_RUN_PATH' >> $MPI_PROFILE && \
    echo 'export OMPI_ALLOW_RUN_AS_ROOT=1' >> $MPI_PROFILE && \
    echo 'export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1' >> $MPI_PROFILE

WORKDIR $INSTALL_BASE_DIR

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV OMPI_ALLOW_RUN_AS_ROOT="1"
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM="1"

COPY ring.c /opt/ring.c
RUN "$MPIHOME/bin/mpicc" "$INSTALL_BASE_DIR/ring.c" -o "$INSTALL_BASE_DIR/ring"

# CMD []
# ENTRYPOINT ["/entrypoint.sh"]
