import sys
import typing as t
from pathlib import Path

import typer

from cstar.base.utils import _run_cmd

app = typer.Typer()


@app.command()
def plan(
    path: t.Annotated[
        Path,
        typer.Argument(help="Path to a blueprint file."),
    ],
    output_dir: t.Annotated[
        Path,
        typer.Argument(help="Path to a directory where the plan will be stored."),
    ],
    transform: t.Annotated[
        bool,
        typer.Option(
            help="Apply runtime transformations to the workplan before rendering."
        ),
    ] = False,
) -> None:
    """Review the execution plan generated by a workplan."""
    transform_clause = "--transform" if transform else "--no-transform"
    stdout = _run_cmd(
        f"{sys.executable} -m cstar.entrypoint.cli.plan {path} {output_dir} {transform_clause}"
    )
    print(stdout)
